apiVersion: v1
kind: Service
metadata:
  name: james-nginx-svc
  labels:
    app: nginx
spec:
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
